---

- name: Get iptables rules
  shell: iptables-save > {{iptables_rule_path}}

- name: Add iptables rules
  lineinfile:
    dest={{iptables_rule_path}}
    regexp="^-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
    line="-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
    insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
  notify: iptables reload
  with_items: iptables_rules

- name: Enable autosave - pt. 1
  template: src=iptables_load.j2 dest=/etc/network/if-up.d/iptables_load owner=root group=root mode=751
  when: iptables_autosave

- name: Enable autosave - pt. 2
  template: src=iptables_save.j2 dest=/etc/network/if-down.d/iptables_save owner=root group=root mode=751
  when: iptables_autosave
